# Generated by Django 6.0.3 on 2026-05-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique 7-digit order identifier', max_length=7, null=True, unique=True),
        ),
    ]
