# Generated by Django 6.0.3 on 2026-05-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session identifier', max_length=255, null=True),
        ),
    ]
